//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MSLCoach.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MSLCOACH_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDB_BKFIELD                     129
#define IDB_YELBKFIELD                  129
#define IDB_OFFLINE                     130
#define IDB_ONLINE                      131
#define IDB_BLUEBKFIELD                 133
#define IDB_L2RBKFIELD                  136
#define IDB_R2LBKFIELD                  137
#define IDD_COLORDLG                    138
#define IDD_DLGREFINFO                  140
#define IDD_DLG_DEBUG                   141
#define IDC_FULLFIELD                   1000
#define IDC_AG1                         1001
#define IDC_AG2                         1002
#define IDC_AG3                         1003
#define IDC_AG4                         1004
#define IDC_AG5                         1005
#define IDC_AG6                         1006
#define IDC_RECLIST                     1007
#define IDC_SENDLIST                    1008
#define IDC_REFIP                       1009
#define IDC_REFPORT                     1010
#define IDC_CONNECTREF                  1011
#define IDC_REFLIST                     1012
#define IDC_DIS1                        1013
#define IDC_DIS2                        1014
#define IDC_AGENTATTACK                 1015
#define IDC_DIS3                        1016
#define IDC_DIS4                        1017
#define IDC_DIS5                        1018
#define IDC_DIS6                        1019
#define IDC_AGENTSTOP                   1020
#define IDC_SELNUM                      1021
#define IDC_CAMPCOMBO                   1022
#define IDC_OWNGOALCOMBO                1023
#define IDC_CAMPDIS                     1024
#define IDC_OWNGOAL                     1025
#define IDC_REFKICKOFF                  1026
#define IDC_C_FK                        1027
#define IDC_C_GK                        1028
#define IDC_C_TI                        1029
#define IDC_C_CK                        1030
#define IDC_C_P                         1031
#define IDC_M_KO                        1032
#define IDC_M_FK                        1033
#define IDC_M_GK                        1034
#define IDC_M_TI                        1035
#define IDC_M_CK                        1036
#define IDC_M_P                         1037
#define IDC_REF_DB                      1038
#define IDC_REF_START                   1039
#define IDC_REF_STOP                    1040
#define IDC_AGGOALKEEP                  1041
#define IDC_AGKICKOFF                   1042
#define IDC_AGKO_SL                     1043
#define IDC_DEFENCE                     1044
#define IDC_AGKO_SL_START               1045
#define IDC_KO_START                    1046
#define IDC_ATTENTION                   1047
#define IDC_DEFANG                      1048
#define IDC_PRODEF                      1049
#define IDC_MOVETOANGLE                 1050
#define IDC_UPDATEANG                   1051
#define IDC_ASEARCHBALL                 1052
#define IDC_AGKICKOUT                   1053
#define IDC_MULTIDEF                    1054
#define IDC_MULTIATK                    1055
#define IDC_MULTITEST                   1056
#define IDC_AGINFOLIST                  1057
#define IDC_READY                       1058
#define IDC_DEFDIST                     1059
#define IDC_CNTLIST                     1060
#define IDC_SCANAGENT                   1061
#define IDC_CHANGEGOAL                  1062
#define IDC_HFLIP                       1063
#define IDC_VFLIP                       1064
#define IDC_SEPARATOR                   1065
#define IDC_ALLFLIP                     1065
#define IDC_EXPAND                      1066
#define IDC_DISTMDEF                    1067
#define IDC_CHECK_IPFILTER              1068
#define IDC_midpassx                    1069
#define IDC_ADDALLTOCREDIT              1070
#define IDC_midpassy                    1071
#define IDC_CREDITLIST                  1072
#define IDC_MOVETOTEST                  1073
#define IDC_CLEARCREDIT                 1075
#define IDC_CLEARALLCREDIT              1076
#define IDC_ADDTOCREDIT                 1077
#define IDC_KFIELD                      1078
#define IDC_UPDATEK                     1079
#define IDC_REFINFODIS                  1081
#define IDC_PR_OUT                      1082
#define IDC_PR_READY                    1083
#define IDC_SETPLAYERINPONT             1084
#define IDC_CHECK_OBST_ORG              1085
#define IDC_VIEW                        1086
#define IDC_DISDLGDBG                   1087
#define IDC_PROCVIEW                    1088
#define IDC_SLIDER_TH                   1089
#define IDC_EDIT_TH                     1090
#define IDC_TCDEMO                      1091
#define IDC_AG_CATCH                    1092
#define IDC_COVERTHEBALL                1093
#define IDC_DISCONNECTREF               1094
#define IDC_OBSTCONFIG                  1095
#define IDC_TACLIST                     1096
#define IDC_PASSANDCATCH                1097
#define IDC_CONF1_ATK                   1098
#define IDC_CONF1_DEF                   1099
#define IDC_CONF1                       1100
#define IDC_CONF2_ATK1                  1101
#define IDC_CONF2_ATK2                  1102
#define IDC_CONF2                       1103
#define IDC_CONF1_DEFANG                1104
#define IDC_CONF1_DEFDIST               1105
#define IDC_OUTFIELD                    1106
#define IDC_TCDEMO2                     1107
#define IDC_TCDEMO3                     1108
#define IDC_BUTTON1                     1109
#define IDC_EDIT1                       1110
#define IDC_EDIT2                       1111
#define IDC_BUTTON3                     1114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
